using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace AHAKuo.Signalia.Framework
{
    public static class GraphicLoader
    {
        public static Texture2D LoadByName(string n) => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.GRAPHICS_PATH + n, typeof(Texture2D));
        public static Texture2D Signalia => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SIGNALIA, typeof(Texture2D));
        public static Texture2D SignaliaSettings => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_SETTINGS, typeof(Texture2D));
        public static Texture2D SignaliaPackages => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SIGNALIA_PACKAGES, typeof(Texture2D));
        public static Texture2D SystemVitals => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SYSTEM_VITALS, typeof(Texture2D));
        public static Texture2D UIViewHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIVIEW, typeof(Texture2D));
        public static Texture2D UIViewGroupHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIVIEWGROUP, typeof(Texture2D));
        public static Texture2D UIButtonHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIBUTTON, typeof(Texture2D));
        public static Texture2D UIToggleGroupHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UITOGGLEGROUP, typeof(Texture2D));
        public static Texture2D UIFillHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIFILL, typeof(Texture2D));
        public static Texture2D UIAnimatableHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIANIMATABLE, typeof(Texture2D));
        public static Texture2D EventionBoxHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_EVENTIONBOX, typeof(Texture2D));
        public static Texture2D AudioAssetHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_AUDIOSET, typeof(Texture2D));
        public static Texture2D AudioMixerAssetHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_AUDIO_MIXER, typeof(Texture2D));
        public static Texture2D UIAnimationAssetHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COREA_UIANIMATIONASSET, typeof(Texture));
        public static Texture2D GameSavingHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_GAMESAVING, typeof(Texture2D));
        public static Texture2D ResonanceHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_RESONANCE, typeof(Texture2D));
        public static Texture2D ResonanceSettings => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_RESONANCE_SETTINGS, typeof(Texture2D));
        public static Texture2D ResonanceSenders => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.SENDERS_RESONANCE, typeof(Texture2D));
        public static Texture2D ResonanceListeners => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.LISTENERS_RESONANCE, typeof(Texture2D));
        public static Texture2D ResponderObject => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.RESPONDER_OBJECT, typeof(Texture2D));
        public static Texture2D ResponderNoObject => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.RESPONDER_NOOBJECT, typeof(Texture2D));
        public static Texture2D UIElementHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_UIELEMENT, typeof(Texture2D));
        public static Texture2D UtilitiesNotes => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_UTILITY_NOTES, typeof(Texture2D));
        public static Texture2D SmallAnimationHovering => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SMALLANIMATION_HOVERING, typeof(Texture2D));
        public static Texture2D SmallAnimationRotation => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SMALLANIMATION_ROTATION, typeof(Texture2D));
        public static Texture2D SmallAnimationScale => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_SMALLANIMATION_SCALE, typeof(Texture2D));
        public static Texture2D FakePhysicsHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_FAKE_PHYSICS, typeof(Texture2D));
        public static Texture2D AnimatableHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_ANIMATABLE, typeof(Texture2D));
        public static Texture2D AnimationAssetHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_ANIMATIONASSET, typeof(Texture2D));
        public static Texture2D LocalizationHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION, typeof(Texture2D));
        public static Texture2D LocalizationLocbook => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_LOCBOOK, typeof(Texture2D));
        public static Texture2D LocalizationTextStyle => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_TEXTSTYLE, typeof(Texture2D));
        public static Texture2D LocalizationText => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_TEXT, typeof(Texture2D));
        public static Texture2D LocalizationTextSimple => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_TEXTSIMPLE, typeof(Texture2D));
        public static Texture2D LocalizationAudio => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_AUDIO, typeof(Texture2D));
        public static Texture2D LocalizationImage => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_IMAGE, typeof(Texture2D));
        public static Texture2D LocalizationRefresh => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_REFRESH, typeof(Texture2D));
        public static Texture2D LocalizationSwitch => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_SWITCH, typeof(Texture2D));
        public static Texture2D LocalizationLingramiaIcon => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOCALIZATION_LINGRAMIA_ICON, typeof(Texture2D));
        public static Texture2D AudioLayeringHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_AUDIOLAYERING, typeof(Texture2D));
        public static Texture2D AudioLayeringLayerDataHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_AUDIOLAYERING_LAYERDATA, typeof(Texture2D));
        public static Texture2D RoomAudioHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_AUDIOLAYERING_ROOM, typeof(Texture2D));
        public static Texture2D AmbientAudioHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_AUDIOLAYERING_AMBIENT, typeof(Texture2D));
        public static Texture2D DialogueHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_DIALOGUE, typeof(Texture2D));
        public static Texture2D DialogueBookHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_DIALOGUE_DLGBOOK, typeof(Texture2D));
        public static Texture2D DialogueSpokesmanIcon => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_DIALOGUE_SPOKESMAN_ICON, typeof(Texture2D));
        public static Texture2D DialogueStarterHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_DIALOGUE_STARTER, typeof(Texture2D));
        public static Texture2D InventoryHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_INVENTORY, typeof(Texture2D));
        public static Texture2D PoolingHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_POOLING, typeof(Texture2D));
        public static Texture2D PoolingCallerScriptHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_POOLING_CALLERSCRIPT, typeof(Texture2D));
        public static Texture2D LoadingScreenHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_LOADINGSCREEN, typeof(Texture2D));
        public static Texture2D TutorialHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_TUTORIAL, typeof(Texture2D));
        public static Texture2D ResourceCachingHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_RESOURCE_CACHING, typeof(Texture2D));
        public static Texture2D ResourceCachingAsset => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_RESOURCE_CACHING_ASSET, typeof(Texture2D));
        public static Texture2D AudioPlayerHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.AUDIO_PLAYER_HEADER, typeof(Texture2D));
        public static Texture2D HapticScriptHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HAPTIC_SCRIPT_HEADER, typeof(Texture2D));
        public static Texture2D VFXSFXHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.VFXSFX_HEADER, typeof(Texture2D));
        public static Texture2D CommonMechanicsHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_COMMON_MECHANICS, typeof(Texture2D));
        public static Texture2D AchievementSystemHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_ACHIEVEMENT_SYSTEM, typeof(Texture2D));
        public static Texture2D AchievementSOHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.ACH_ACHIEVEMENT_SO, typeof(Texture2D));
        public static Texture2D HealthSystemHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_HEALTH_SYSTEM, typeof(Texture2D));
        public static Texture2D DamagerHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HLTH_DAMAGER, typeof(Texture2D));
        public static Texture2D ObjectHealthHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HLTH_OBJECT_HEALTH, typeof(Texture2D));
        public static Texture2D CameraSystemHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_CAMERA_SYSTEM, typeof(Texture2D));
        public static Texture2D TargetCamera3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.CAM_TARGET_CAMERA_3D, typeof(Texture2D));
        public static Texture2D MovementSystemHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_MOVEMENT_SYSTEM, typeof(Texture2D));
        public static Texture2D MovementModifier3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_MOVEMENT_MODIFIER_3D, typeof(Texture2D));
        public static Texture2D MovementPhysics3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_MOVEMENT_PHYSICS_3D, typeof(Texture2D));
        public static Texture2D JumpModifier3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_JUMP_MODIFIER_3D, typeof(Texture2D));
        public static Texture2D DashModifier3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_DASH_MODIFIER_3D, typeof(Texture2D));
        public static Texture2D DebugModifier3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_DEBUG_MODIFIER_3D, typeof(Texture2D));
        public static Texture2D ConstraintModifier3DHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.MVM_CONSTRAINT_MODIFIER_3D, typeof(Texture2D));
        public static Texture2D EntityHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_ENTITY_SYSTEM, typeof(Texture2D));
        public static Texture2D EntityLogicHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.ENT_ENTITY_LOGIC, typeof(Texture2D));
        public static Texture2D EntityComponentHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.ENT_ENTITY_COMPONENT, typeof(Texture2D));
        public static Texture2D NotificationSystemHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_NOTIFICATION_SYSTEM, typeof(Texture2D));
        public static Texture2D SystemMessageHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.NOT_SYSTEM_MESSAGE, typeof(Texture2D));
        public static Texture2D BurnerSpotHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.NOT_BURNER_SPOT, typeof(Texture2D));
        public static Texture2D BurnerObjectHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.NOT_BURNER_OBJECT, typeof(Texture2D));
        public static Texture2D ActionMapHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_ACTION_MAP, typeof(Texture2D));
        public static Texture2D CMN_CurrenciesSpawner => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.CMN_CURRENCIES_SPAWNER, typeof(Texture2D));
        public static Texture2D CMN_Triggerbox => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.CMN_TRIGGERBOX, typeof(Texture2D));
        public static Texture2D CMN_InteractiveZone => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.CMN_INTERACTIVE_ZONE, typeof(Texture2D));
        public static Texture2D CMN_BlowUpSpawner => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.CMN_BLOWUP_SPAWNER, typeof(Texture2D));
        public static Texture2D InlineScriptHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.INLINE_SCRIPT_HEADER, typeof(Texture2D));
        public static Texture2D InventoryGameSlotHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.INVENTORY_GAME_SLOT_HEADER, typeof(Texture2D));
        public static Texture2D InventoryGameGridHeader  => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.INVENTORY_GAME_GRID_HEADER, typeof(Texture2D));
        public static Texture2D InventoryGameDisplayerHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.INVENTORY_GAME_DISPLAYER_HEADER, typeof(Texture2D));
        public static Texture2D InventoryGameInvHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.INVENTORY_GAME_INV_HEADER, typeof(Texture2D));
        public static Texture2D IntroduceNewAudioHeader => (Texture2D)AssetDatabase.LoadAssetAtPath(FrameworkConstants.GraphicPaths.HEADER_INTRODUCE_NEW_AUDIO, typeof(Texture2D));
    }
}
