using System;
using System.Text;
using UnityEngine;

namespace AHAKuo.Signalia.GameSystems.InlineScript.Internal.Utils
{
    public static class CodeWriter
    {
        /// <summary>
        /// Common usings for generated scripts. So that the user can have a familiar environment for mostly accessed stuff.
        /// </summary>
        public const string TemplateUsings =
            "using System;\n" +
            "using System.Collections;\n" +
            "using System.Collections.Generic;\n" +
            "using System.Linq;\n" +
            "using UnityEngine;\n" +
            "using UnityEngine.SceneManagement;\n" +
            "using UnityEngine.UI;\n" +
            "using AHAKuo.Signalia.GameSystems.InlineScript.Internal.Utils;\n" +
            "using Random = UnityEngine.Random;\n";

        public static string ScriptHeader =
            "// This code is generated by InlineScript at runtime. Do not modify this file directly.\n" +
            "// Generated / Last Updated on: " + DateTime.Now.ToLongDateString() + " | " + DateTime.Now.ToLongTimeString() + ".\n";

        public const string NamespaceDeclaration = "namespace AHAKuo.Signalia.GameSystems.InlineScript.External.Generated\n{\n";

        private const string CommentSectionPrefix = "// @InlineScript Section:";
        private const string CommentSectionSuffix = "// @InlineScript EndSection";

        private static bool AppendOptionalLines(StringBuilder sb, string block)
        {
            if (string.IsNullOrWhiteSpace(block))
            {
                return false;
            }

            var hasContent = false;
            foreach (var line in block.Split('\n'))
            {
                sb.AppendLine(line.TrimEnd('\r'));
                hasContent = true;
            }

            return hasContent;
        }

        private static void AppendCommentSection(StringBuilder sb, string sectionName, string content)
        {
            sb.AppendLine($"{CommentSectionPrefix} {sectionName}");

            if (string.IsNullOrEmpty(content))
            {
                sb.AppendLine("//");
            }
            else
            {
                foreach (var line in content.Split('\n'))
                {
                    var sanitized = line.TrimEnd('\r');
                    if (string.IsNullOrEmpty(sanitized))
                    {
                        sb.AppendLine("//");
                    }
                    else
                    {
                        sb.Append("// ").AppendLine(sanitized);
                    }
                }
            }

            sb.AppendLine(CommentSectionSuffix);
            sb.AppendLine();
        }

        private static void AppendCachedDefinitions(StringBuilder sb, string cachedDefinitions)
        {
            if (string.IsNullOrWhiteSpace(cachedDefinitions))
            {
                return;
            }

            foreach (var line in cachedDefinitions.Split('\n'))
            {
                var sanitized = line.TrimEnd('\r');
                if (string.IsNullOrEmpty(sanitized))
                {
                    sb.AppendLine();
                }
                else
                {
                    sb.Append("    ").AppendLine(sanitized);
                }
            }

            sb.AppendLine();
        }

        public static void InlineScript_Append1(this StringBuilder sb, string userCode, string additionalUsings,
            string cachedDefinitions, string globalUsings)
        {
            sb.AppendLine(TemplateUsings);

            var hasAdditional = AppendOptionalLines(sb, globalUsings);
            hasAdditional |= AppendOptionalLines(sb, additionalUsings);
            if (hasAdditional)
            {
                sb.AppendLine();
            }

            sb.AppendLine(ScriptHeader);
            AppendCommentSection(sb, "Global Imports", globalUsings);
            AppendCommentSection(sb, "Additional Usings", additionalUsings);
            AppendCommentSection(sb, "Cached Definitions", cachedDefinitions);
            AppendCommentSection(sb, "User Code", userCode);

            sb.AppendLine(NamespaceDeclaration);
        }

        /// <summary>
        /// Builds the boilerplate script dynamically without using string.Format.
        /// </summary>
        /// <param name="className">The name of the class to generate</param>
        /// <param name="userCode">The user's inline code to wrap</param>
        /// <returns>The complete generated script content</returns>
        public static string BoilerPlateVoid(string className, string userCode, string additionalUsings,
            string cachedDefinitions, string globalUsings)
        {
            var sb = new StringBuilder(512);

            sb.InlineScript_Append1(userCode, additionalUsings, cachedDefinitions, globalUsings);
            sb.Append("    public class ").Append(className).AppendLine(" : ").Append(InlineScriptConstants.VoidBoilerPlateClass);
            sb.AppendLine("    {");
            AppendCachedDefinitions(sb, cachedDefinitions);
            sb.AppendLine("        public override void ExecuteCode(GameObject gameObject)");
            sb.AppendLine("        {");

            // base invoke
            sb.AppendLine("            base.ExecuteCode(gameObject);");
            sb.AppendLine();

            // ensure correct indentation and clean line endings
            if (!string.IsNullOrWhiteSpace(userCode))
            {
                foreach (var line in userCode.Split('\n'))
                    sb.Append("            ").AppendLine(line.TrimEnd('\r'));
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        public static string BoilerPlateFunction(string className, string userCode, string additionalUsings,
            string cachedDefinitions, string globalUsings, string baseClassName, string returnType, string methodName)
        {
            var sb = new StringBuilder(512);

            sb.InlineScript_Append1(userCode, additionalUsings, cachedDefinitions, globalUsings);
            sb.Append("    public class ").Append(className).Append(" : ").Append(baseClassName).AppendLine();
            sb.AppendLine("    {");
            AppendCachedDefinitions(sb, cachedDefinitions);
            sb.Append("        public override ").Append(returnType).Append(' ').Append(methodName).AppendLine("(GameObject gameObject)");
            sb.AppendLine("        {");
            sb.AppendLine("            base.Evaluate(gameObject);");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(userCode))
            {
                foreach (var line in userCode.Split('\n'))
                {
                    sb.Append("            ").AppendLine(line.TrimEnd('\r'));
                }
                sb.AppendLine();
            }
            // No implicit default return; user code should return a value.
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

    }
}
